logging:
  level:
    root: info
    web: info

spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/test_db
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

custom:
  region: EU
  environment: TEST