spring:
  mvc:
    servlet:
      path: /api
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: spring_native_reference_project

springdoc:
  swagger-ui:
    path: /swagger
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always

server:
  error:
    whitelabel:
      enabled: false
