version: '3.9'

services:

  postgresql:
    image: postgres:13.5
    container_name: postgresql
    hostname: postgresql
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - '5432:5432'

  wiremock:
    image: wiremock/wiremock:2.30.1
    container_name: wiremock
    hostname: wiremock
    command:
      - --verbose
    volumes:
      - ./wiremock/:/home/wiremock:ro
    ports:
      - '8081:8080'

  localstack:
    image: localstack/localstack:0.12.20
    container_name: localstack
    hostname: localstack
    environment:
      SERVICES: iam,sqs,sns,sts
      DEBUG: 1
      EDGE_PORT: 4566
      DEFAULT_REGION: eu-central-1
      INIT_SCRIPTS_PATH: /docker-entrypoint-initaws.d
      ENFORCE_IAM: 1
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d:ro
    ports:
      - "4566:4566"
