apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-native-reference-project
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: spring-native-reference-project
          args:
            - -Dspring.profiles.active="EU-TEST"
