logging:
  level:
    root: info
    web: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    hikari:
      schema: spring_native_reference_project
    username: test
    password: test